# Generated by Django 2.2.16 on 2022-07-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20220711_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.TextField(blank=True, help_text='Придумайте краткое описание вашего поста', max_length=20, verbose_name='Оглавление ващей записи'),
        ),
    ]
