# Generated by Django 2.2.6 on 2022-07-15 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.IntegerField(blank=True, default=1, verbose_name='Лайк'),
            preserve_default=False,
        ),
    ]
