# Generated by Django 2.2.16 on 2022-07-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like',
            field=models.IntegerField(blank=True, verbose_name='Like'),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
