# Generated by Django 2.2.16 on 2022-07-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_edit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileedit',
            name='description',
            field=models.TextField(default=1, help_text='Расскажите немного о себе и вашем контенте', verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
